# Add a function called resumo() to the moeda.py module created in the previous challenges, 
# which displays some information generated by the functions we already have in the module so far.

import currency_bruno

n = int(input('Type here: '))
currency_bruno.current_resume(n,80,10)